production:
  SECRET_KEY_BASE: 0bf24c1216facbfb2dae96ee2365caad5e244a4617ba3b574be384427f4380ccd24f8e73f9e5aeca2b828a764e1221322138e7c979afb694be1db79007bcb303
  REDIS_HOST: redis
  REDIS_PORT: 6379
  DATABASE_HOST: db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

development:
  SECRET_KEY_BASE: 0bf24c1216facbfb2dae96ee2365caad5e244a4617ba3b574be384427f4380ccd24f8e73f9e5aeca2b828a764e1221322138e7c979afb694be1db79007bcb303
  REDIS_HOST: redis
  REDIS_PORT: 6379
  DATABASE_HOST: localhost
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  
test:
  SECRET_KEY_BASE: 0bf24c1216facbfb2dae96ee2365caad5e244a4617ba3b574be384427f4380ccd24f8e73f9e5aeca2b828a764e1221322138e7c979afb694be1db79007bcb303