default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { 'localhost' } %> 
  username: <%= ENV.fetch("POSTGRES_USER") { 'postgres' } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { 'postgres' } %>
  # host: localhost
  port: 5432

development:
  <<: *default
  database: mail_parser_app_development
  
test:
  <<: *default
  database: mail_parser_app_test

production:
  primary: &primary_production
    <<: *default
    database: mail_parser_app_production
  cache:
    <<: *primary_production
    database: mail_parser_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: mail_parser_app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: mail_parser_app_production_cable
    migrations_paths: db/cable_migrate
